name: Metrics
on:
  schedule: 
    - cron: '0 0,12 * * *'

  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: UTTAM-VAGHASIA
          template: classic
          base: metadata
          config_timezone: Asia/Calcutta
          config_display: large
          
          # Features
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          output_action: commit
          filename: assets/github-metrics.svg
