name: Waka Readme

on:
  schedule:
    # Executes every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_SHORT_INFO: "True"
          
          # Bar Graph Customization
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_COMMIT_GRAPH: "True"
          
          # Display Settings
          LOCALE: "en"
          COMMIT_BY_ME: "True"
          TIMEZONE: "Asia/Kolkata"
          
          # Custom Bar Characters (Enhanced visuals)
          SYMBOL_VERSION: "2"
          
          # Percentile and Statistics
          SHOW_PERCENT: "True"
          SHOW_TIME: "True"
          
          # Language and Project Limits
          LANGUAGE_COUNT: "10"
          PROJECT_COUNT: "8"
          OS_COUNT: "3"
          EDITOR_COUNT: "3"